//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 01:13:14 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://memorynotfound.com/beer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.memorynotfound.beer;
